permissions:
    actions: read

name: ESLint and Biome
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            # required for all workflows
            security-events: write
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"

            - name: Install modules
              run: npm install

            - name: Run formatter check
              run: npx biome check --formatter-enabled=true --linter-enabled=false .

            - name: Run ESLint
              run: npx eslint --ext ts --color -c .eslintrc.cjs src

            - name: Run TypeScript type check
              run: npx tsc --noEmit
